export const LOAD_ACTIVITIES = 'LOAD_ACTIVITIES';
export const LOAD_ACTIVITY_DETAIL = 'LOAD_ACTIVITY_DETAIL';

export const LOAD_STUDENTS = 'LOAD_STUDENTS';
export const LOAD_APPROVALS = 'LOAD_APPROVALS';
export const LOAD_MANAGERS = 'LOAD_MANAGERS';
